package com.mdframe.forge.plugin.generator.service.lowcode.runtime;

import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * PostgreSQL 运行时方言。
 */
@Component
public class PostgreSqlRuntimeDatabaseDialect implements RuntimeDatabaseDialect {

    @Override
    public String dbType() {
        return "PostgreSQL";
    }

    @Override
    public boolean supports(String dbType) {
        return StringUtils.equalsAnyIgnoreCase(dbType, "postgresql", "postgres");
    }

    @Override
    public String quote(String identifier) {
        return "\"" + StringUtils.defaultString(identifier).replace("\"", "\"\"") + "\"";
    }

    @Override
    public String tableExistsSql() {
        return """
            SELECT COUNT(1)
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = ?
            """;
    }

    @Override
    public String listColumnsSql() {
        return """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = ?
            ORDER BY ordinal_position
            """;
    }

    @Override
    public String listColumnMetadataSql() {
        return """
            SELECT column_name,
                   CASE
                       WHEN data_type IN ('character varying', 'character')
                            AND character_maximum_length IS NOT NULL
                           THEN data_type || '(' || character_maximum_length || ')'
                       ELSE data_type
                   END AS column_type,
                   is_nullable, column_default, '' AS extra,
                   COALESCE(col_description((quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass::oid, ordinal_position), '') AS column_comment,
                   '' AS generation_expression
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = ?
            ORDER BY ordinal_position
            """;
    }

    @Override
    public String listIndexesSql() {
        return """
            SELECT indexname
            FROM pg_indexes
            WHERE schemaname = current_schema()
              AND tablename = ?
            """;
    }

    @Override
    public String primaryKeyMetadataSql() {
        return """
            SELECT kcu.column_name, c.data_type, COALESCE(c.column_default, '') AS extra
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            JOIN information_schema.columns c
              ON c.table_schema = kcu.table_schema
             AND c.table_name = kcu.table_name
             AND c.column_name = kcu.column_name
            WHERE tc.constraint_type = 'PRIMARY KEY'
              AND tc.table_schema = current_schema()
              AND tc.table_name = ?
            ORDER BY kcu.ordinal_position
            """;
    }

    @Override
    public String paginate(String sql, long offset, long limit) {
        return sql + " LIMIT " + limit + " OFFSET " + offset;
    }

    @Override
    public String resolveSqlType(String dataType, int length, String decimalPrecision) {
        return switch (dataType) {
            case "varchar" -> "varchar(" + length + ")";
            case "char" -> "char(" + length + ")";
            case "text", "longtext" -> "text";
            case "date", "time" -> dataType;
            case "datetime" -> "timestamp";
            case "int" -> "integer";
            case "bigint" -> "bigint";
            case "tinyint" -> "smallint";
            case "decimal" -> "numeric(" + decimalPrecision + ")";
            default -> throw new IllegalArgumentException("不支持的数据类型: " + dataType);
        };
    }

    @Override
    public String columnDefinition(DdlColumn column) {
        StringBuilder definition = new StringBuilder();
        definition.append(ddlIdentifier(column.columnName())).append(" ").append(column.sqlType());
        if (column.identity()) {
            definition.append(" GENERATED BY DEFAULT AS IDENTITY");
        }
        appendDefaultValue(definition, column);
        definition.append(column.required() || column.identity() ? " NOT NULL" : " NULL");
        return definition.toString();
    }

    @Override
    public String primaryKeyConstraint(String tableName, String columnName) {
        return "CONSTRAINT " + ddlIdentifier(normalizeObjectName("pk_" + tableName))
            + " PRIMARY KEY (" + ddlIdentifier(columnName) + ")";
    }

    @Override
    public String inlineIndexDefinition(IndexDefinition index) {
        return null;
    }

    @Override
    public String createTableSql(String tableName, List<String> definitions, String tableComment) {
        return "CREATE TABLE IF NOT EXISTS " + ddlIdentifier(tableName) + " (\n  "
            + String.join(",\n  ", definitions)
            + "\n)";
    }

    @Override
    public List<String> afterCreateTableSql(String tableName,
                                            String tableComment,
                                            List<DdlColumn> columns,
                                            List<IndexDefinition> indexes) {
        List<String> statements = new ArrayList<>();
        if (StringUtils.isNotBlank(tableComment)) {
            statements.add("COMMENT ON TABLE " + ddlIdentifier(tableName)
                + " IS '" + escapeSqlComment(tableComment) + "'");
        }
        for (DdlColumn column : columns) {
            if (StringUtils.isNotBlank(column.comment())) {
                statements.add("COMMENT ON COLUMN " + ddlIdentifier(tableName) + "."
                    + ddlIdentifier(column.columnName()) + " IS '" + escapeSqlComment(column.comment()) + "'");
            }
        }
        for (IndexDefinition index : indexes) {
            statements.add(addIndexSql(tableName, index));
        }
        return statements;
    }

    @Override
    public String addColumnSql(String tableName, DdlColumn column) {
        return "ALTER TABLE " + ddlIdentifier(tableName) + " ADD COLUMN " + columnDefinition(column);
    }

    @Override
    public List<String> afterAddColumnSql(String tableName, DdlColumn column) {
        if (StringUtils.isBlank(column.comment())) {
            return List.of();
        }
        return List.of("COMMENT ON COLUMN " + ddlIdentifier(tableName) + "."
            + ddlIdentifier(column.columnName()) + " IS '" + escapeSqlComment(column.comment()) + "'");
    }

    @Override
    public List<String> modifyColumnSql(String tableName, DdlColumn column) {
        List<String> statements = new ArrayList<>();
        statements.add("ALTER TABLE " + ddlIdentifier(tableName) + " ALTER COLUMN "
            + ddlIdentifier(column.columnName()) + " TYPE " + column.sqlType());
        if (column.defaultValue() == null) {
            statements.add("ALTER TABLE " + ddlIdentifier(tableName) + " ALTER COLUMN "
                + ddlIdentifier(column.columnName()) + " DROP DEFAULT");
        } else {
            statements.add("ALTER TABLE " + ddlIdentifier(tableName) + " ALTER COLUMN "
                + ddlIdentifier(column.columnName()) + " SET DEFAULT " + defaultLiteral(column));
        }
        statements.add("ALTER TABLE " + ddlIdentifier(tableName) + " ALTER COLUMN "
            + ddlIdentifier(column.columnName()) + (column.required() ? " SET NOT NULL" : " DROP NOT NULL"));
        if (StringUtils.isNotBlank(column.comment())) {
            statements.add("COMMENT ON COLUMN " + ddlIdentifier(tableName) + "."
                + ddlIdentifier(column.columnName()) + " IS '" + escapeSqlComment(column.comment()) + "'");
        }
        return statements;
    }

    @Override
    public String addIndexSql(String tableName, IndexDefinition index) {
        String columns = index.columns().stream()
            .map(this::ddlIdentifier)
            .collect(Collectors.joining(", "));
        return "CREATE " + (index.unique() ? "UNIQUE " : "") + "INDEX "
            + ddlIdentifier(normalizeObjectName(index.indexName())) + " ON "
            + ddlIdentifier(tableName) + " (" + columns + ")";
    }

    @Override
    public boolean sameSqlType(String expected, String actual) {
        return normalizePostgresType(expected).equals(normalizePostgresType(actual));
    }

    @Override
    public String listImportTablesSql() {
        return """
            SELECT table_name,
                   COALESCE(obj_description((quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass::oid), table_name) AS table_comment,
                   NULL::timestamp AS create_time,
                   NULL::timestamp AS update_time
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_type = 'BASE TABLE'
              AND table_name NOT LIKE 'qrtz_%'
              AND table_name NOT LIKE 'gen_%'
            ORDER BY table_name
            """;
    }

    @Override
    public String importTableInfoSql() {
        return """
            SELECT table_name,
                   COALESCE(obj_description((quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass::oid), table_name) AS table_comment,
                   NULL::timestamp AS create_time,
                   NULL::timestamp AS update_time
            FROM information_schema.tables
            WHERE table_schema = current_schema()
              AND table_name = ?
            """;
    }

    @Override
    public String listImportColumnsSql() {
        return """
            SELECT c.column_name,
                   COALESCE(col_description((quote_ident(c.table_schema) || '.' || quote_ident(c.table_name))::regclass::oid, c.ordinal_position), '') AS column_comment,
                   CASE
                       WHEN c.data_type = 'character varying' THEN 'varchar(' || c.character_maximum_length || ')'
                       WHEN c.data_type = 'character' THEN 'char(' || c.character_maximum_length || ')'
                       WHEN c.data_type = 'numeric' THEN 'numeric(' || c.numeric_precision || ',' || c.numeric_scale || ')'
                       ELSE c.data_type
                   END AS column_type,
                   CASE WHEN kcu.column_name IS NOT NULL THEN 1 ELSE 0 END AS is_pk,
                   CASE WHEN c.column_default LIKE 'nextval%%' OR c.is_identity = 'YES' THEN 1 ELSE 0 END AS is_increment,
                   CASE WHEN c.is_nullable = 'NO' AND kcu.column_name IS NULL THEN 1 ELSE 0 END AS is_required
            FROM information_schema.columns c
            LEFT JOIN information_schema.table_constraints tc
              ON tc.table_schema = c.table_schema
             AND tc.table_name = c.table_name
             AND tc.constraint_type = 'PRIMARY KEY'
            LEFT JOIN information_schema.key_column_usage kcu
              ON kcu.table_schema = tc.table_schema
             AND kcu.table_name = tc.table_name
             AND kcu.constraint_name = tc.constraint_name
             AND kcu.column_name = c.column_name
            WHERE c.table_schema = current_schema()
              AND c.table_name = ?
            ORDER BY c.ordinal_position
            """;
    }

    private void appendDefaultValue(StringBuilder definition, DdlColumn column) {
        if (column.defaultValue() == null || "text".equalsIgnoreCase(column.sqlType())) {
            return;
        }
        definition.append(" DEFAULT ").append(defaultLiteral(column));
    }

    private String defaultLiteral(DdlColumn column) {
        String value = Objects.toString(column.defaultValue(), "").trim();
        if (isExpressionDefault(value) || isNumericType(column.sqlType())) {
            return value;
        }
        return "'" + escapeSqlComment(value) + "'";
    }

    private boolean isNumericType(String sqlType) {
        String normalized = StringUtils.defaultString(sqlType).toLowerCase(Locale.ROOT);
        return normalized.startsWith("integer")
            || normalized.startsWith("bigint")
            || normalized.startsWith("smallint")
            || normalized.startsWith("numeric");
    }

    private boolean isExpressionDefault(String value) {
        String normalized = StringUtils.defaultString(value).trim().toUpperCase(Locale.ROOT);
        return normalized.equals("CURRENT_TIMESTAMP")
            || normalized.equals("CURRENT_DATE")
            || normalized.equals("CURRENT_TIME")
            || normalized.equals("NOW()");
    }

    private String normalizeObjectName(String value) {
        String normalized = StringUtils.defaultString(value)
            .replaceAll("[^a-zA-Z0-9_]", "_")
            .replaceAll("_+", "_")
            .toLowerCase(Locale.ROOT);
        if (normalized.length() > maxIdentifierLength()) {
            return normalized.substring(0, maxIdentifierLength());
        }
        return normalized;
    }

    private String normalizePostgresType(String value) {
        String normalized = Objects.toString(value, "")
            .toLowerCase(Locale.ROOT)
            .replaceAll("\\s+", "");
        if (normalized.startsWith("charactervarying(")) {
            return normalized.replace("charactervarying", "varchar");
        }
        if (normalized.equals("timestampwithouttimezone")) {
            return "timestamp";
        }
        if (normalized.equals("integer")) {
            return "int";
        }
        if (normalized.equals("numeric")) {
            return "decimal";
        }
        if (normalized.startsWith("numeric(")) {
            return normalized.replace("numeric", "decimal");
        }
        return normalized;
    }

    private String escapeSqlComment(String value) {
        return StringUtils.defaultString(value).replace("'", "''");
    }
}
