-- 业务应用平台主数据表。

CREATE TABLE IF NOT EXISTS `ai_business_suite` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户ID',
  `suite_code` varchar(48) NOT NULL COMMENT '业务套件编码',
  `suite_name` varchar(128) NOT NULL COMMENT '业务套件名称',
  `icon` varchar(128) DEFAULT NULL COMMENT '套件图标',
  `description` varchar(500) DEFAULT NULL COMMENT '业务说明',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `options` json DEFAULT NULL COMMENT '扩展配置',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_business_suite_code` (`tenant_id`, `suite_code`),
  KEY `idx_ai_business_suite_status` (`tenant_id`, `status`, `sort_order`),
  KEY `idx_ai_business_suite_update` (`tenant_id`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI业务应用平台-业务套件表';

CREATE TABLE IF NOT EXISTS `ai_business_object` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户ID',
  `suite_code` varchar(48) NOT NULL COMMENT '所属业务套件编码',
  `object_code` varchar(48) NOT NULL COMMENT '业务对象编码',
  `object_name` varchar(128) NOT NULL COMMENT '业务对象名称',
  `object_type` varchar(32) NOT NULL COMMENT '对象类型：MASTER/DETAIL/LOOKUP/TRANSACTION',
  `model_id` bigint DEFAULT NULL COMMENT '关联低代码模型ID',
  `model_code` varchar(48) DEFAULT NULL COMMENT '关联低代码模型编码',
  `display_field` varchar(64) DEFAULT NULL COMMENT '默认展示字段',
  `icon` varchar(128) DEFAULT NULL COMMENT '对象图标',
  `description` varchar(500) DEFAULT NULL COMMENT '业务说明',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `options` json DEFAULT NULL COMMENT '扩展配置',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_business_object_code` (`tenant_id`, `suite_code`, `object_code`),
  KEY `idx_ai_business_object_suite` (`tenant_id`, `suite_code`, `status`, `sort_order`),
  KEY `idx_ai_business_object_model` (`tenant_id`, `model_id`),
  KEY `idx_ai_business_object_update` (`tenant_id`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI业务应用平台-业务对象表';

CREATE TABLE IF NOT EXISTS `ai_business_object_relation` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户ID',
  `suite_code` varchar(48) NOT NULL COMMENT '所属业务套件编码',
  `source_object_code` varchar(48) NOT NULL COMMENT '来源业务对象编码',
  `target_object_code` varchar(48) NOT NULL COMMENT '目标业务对象编码',
  `relation_type` varchar(32) NOT NULL COMMENT '关系类型：REFERENCE/DETAIL/CHILD_LIST/MANY_TO_MANY',
  `relation_name` varchar(128) NOT NULL COMMENT '关系名称',
  `source_field_code` varchar(64) DEFAULT NULL COMMENT '来源对象字段编码',
  `target_field_code` varchar(64) DEFAULT NULL COMMENT '目标对象字段编码',
  `relation_config` json DEFAULT NULL COMMENT '关系配置',
  `description` varchar(500) DEFAULT NULL COMMENT '关系说明',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_business_relation_scope` (`tenant_id`, `suite_code`, `source_object_code`, `target_object_code`, `relation_type`, `relation_name`),
  KEY `idx_ai_business_relation_source` (`tenant_id`, `suite_code`, `source_object_code`, `status`),
  KEY `idx_ai_business_relation_target` (`tenant_id`, `suite_code`, `target_object_code`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI业务应用平台-业务对象关系表';

CREATE TABLE IF NOT EXISTS `ai_business_app` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户ID',
  `app_code` varchar(64) NOT NULL COMMENT '应用入口编码',
  `app_name` varchar(128) NOT NULL COMMENT '应用入口名称',
  `app_type` varchar(32) NOT NULL COMMENT '应用类型：BUSINESS/EMBEDDED/MOBILE/INTEGRATION',
  `suite_code` varchar(48) NOT NULL COMMENT '所属业务套件编码',
  `object_code` varchar(48) DEFAULT NULL COMMENT '关联业务对象编码',
  `entry_mode` varchar(32) NOT NULL COMMENT '入口模式：RUNTIME/ROUTE/IFRAME/EXTERNAL/H5/API',
  `entry_url` varchar(512) DEFAULT NULL COMMENT '入口地址',
  `config_key` varchar(128) DEFAULT NULL COMMENT '关联低代码运行配置键',
  `icon` varchar(128) DEFAULT NULL COMMENT '应用图标',
  `description` varchar(500) DEFAULT NULL COMMENT '业务说明',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `options` json DEFAULT NULL COMMENT '扩展配置',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_business_app_code` (`tenant_id`, `app_code`),
  KEY `idx_ai_business_app_suite` (`tenant_id`, `suite_code`, `app_type`, `status`, `sort_order`),
  KEY `idx_ai_business_app_object` (`tenant_id`, `suite_code`, `object_code`, `status`),
  KEY `idx_ai_business_app_config_key` (`tenant_id`, `config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI业务应用平台-应用入口表';

CREATE TABLE IF NOT EXISTS `ai_business_binding` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户ID',
  `target_type` varchar(32) NOT NULL COMMENT '挂接目标类型：SUITE/OBJECT/APP',
  `target_id` bigint DEFAULT NULL COMMENT '挂接目标ID',
  `target_code` varchar(128) NOT NULL COMMENT '挂接目标编码',
  `binding_type` varchar(32) NOT NULL COMMENT '能力类型：FLOW/APPROVAL/REPORT/PERMISSION/MESSAGE/TRIGGER/IMPORT/EXPORT/MOBILE/INTEGRATION',
  `binding_key` varchar(128) NOT NULL COMMENT '能力业务键',
  `binding_name` varchar(128) NOT NULL COMMENT '挂接名称',
  `binding_config` json DEFAULT NULL COMMENT '挂接配置',
  `description` varchar(500) DEFAULT NULL COMMENT '挂接说明',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1启用 0禁用',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_dept` bigint DEFAULT NULL COMMENT '创建部门',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_business_binding_target` (`tenant_id`, `target_type`, `target_code`, `binding_type`, `binding_key`),
  KEY `idx_ai_business_binding_target_id` (`tenant_id`, `target_type`, `target_id`, `binding_type`),
  KEY `idx_ai_business_binding_type` (`tenant_id`, `binding_type`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI业务应用平台-能力挂接表';
