-- CRM 核心运行表
-- 为 CRM 可交付闭环补齐真实运行表

-- 客户表
CREATE TABLE IF NOT EXISTS `crm_customer` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户编号',
    `customer_name` varchar(200) NOT NULL COMMENT '客户名称',
    `customer_code` varchar(100) DEFAULT NULL COMMENT '客户编码',
    `customer_type` varchar(50) DEFAULT 'ENTERPRISE' COMMENT '客户类型：ENTERPRISE-企业，PERSONAL-个人',
    `industry` varchar(100) DEFAULT NULL COMMENT '所属行业',
    `region_code` varchar(20) DEFAULT NULL COMMENT '区域编码',
    `address` varchar(500) DEFAULT NULL COMMENT '详细地址',
    `contact_name` varchar(100) DEFAULT NULL COMMENT '联系人',
    `contact_phone` varchar(50) DEFAULT NULL COMMENT '联系电话',
    `contact_email` varchar(200) DEFAULT NULL COMMENT '联系邮箱',
    `source` varchar(50) DEFAULT NULL COMMENT '客户来源',
    `level` varchar(20) DEFAULT 'NORMAL' COMMENT '客户等级：VIP-重要，NORMAL-普通，POTENTIAL-潜在',
    `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：0-停用，1-启用',
    `owner_id` bigint DEFAULT NULL COMMENT '负责人ID',
    `owner_name` varchar(100) DEFAULT NULL COMMENT '负责人名称',
    `dept_id` bigint DEFAULT NULL COMMENT '部门ID',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `options` text DEFAULT NULL COMMENT '扩展配置JSON',
    `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_dept` bigint DEFAULT NULL COMMENT '创建部门ID',
    `update_by` bigint DEFAULT NULL COMMENT '更新人ID',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-删除',
    PRIMARY KEY (`id`),
    KEY `idx_crm_customer_tenant_id` (`tenant_id`),
    KEY `idx_crm_customer_status` (`tenant_id`, `status`),
    KEY `idx_crm_customer_owner` (`tenant_id`, `owner_id`),
    KEY `idx_crm_customer_create_time` (`tenant_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM客户表';

-- 联系人表
CREATE TABLE IF NOT EXISTS `crm_contact` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户编号',
    `customer_id` bigint NOT NULL COMMENT '客户ID',
    `contact_name` varchar(100) NOT NULL COMMENT '联系人姓名',
    `gender` tinyint DEFAULT NULL COMMENT '性别：0-女，1-男',
    `position` varchar(100) DEFAULT NULL COMMENT '职位',
    `phone` varchar(50) DEFAULT NULL COMMENT '手机号码',
    `telephone` varchar(50) DEFAULT NULL COMMENT '固定电话',
    `email` varchar(200) DEFAULT NULL COMMENT '邮箱',
    `wechat` varchar(100) DEFAULT NULL COMMENT '微信号',
    `is_primary` tinyint NOT NULL DEFAULT '0' COMMENT '是否主联系人：0-否，1-是',
    `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：0-停用，1-启用',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `options` text DEFAULT NULL COMMENT '扩展配置JSON',
    `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_dept` bigint DEFAULT NULL COMMENT '创建部门ID',
    `update_by` bigint DEFAULT NULL COMMENT '更新人ID',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-删除',
    PRIMARY KEY (`id`),
    KEY `idx_crm_contact_tenant_id` (`tenant_id`),
    KEY `idx_crm_contact_customer` (`tenant_id`, `customer_id`),
    KEY `idx_crm_contact_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM联系人表';

-- 商机表
CREATE TABLE IF NOT EXISTS `crm_opportunity` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户编号',
    `customer_id` bigint NOT NULL COMMENT '客户ID',
    `opportunity_name` varchar(200) NOT NULL COMMENT '商机名称',
    `opportunity_code` varchar(100) DEFAULT NULL COMMENT '商机编码',
    `stage` varchar(50) DEFAULT 'INITIAL' COMMENT '商机阶段：INITIAL-初步接触，FOLLOWING-跟进中，NEGOTIATION-商务谈判，CLOSED_WON-赢单，CLOSED_LOST-丢单',
    `amount_cent` bigint DEFAULT '0' COMMENT '预计金额（分）',
    `probability` int DEFAULT '0' COMMENT '赢单概率（0-100）',
    `expected_close_date` date DEFAULT NULL COMMENT '预计成交日期',
    `actual_close_date` date DEFAULT NULL COMMENT '实际成交日期',
    `source` varchar(50) DEFAULT NULL COMMENT '商机来源',
    `owner_id` bigint DEFAULT NULL COMMENT '负责人ID',
    `owner_name` varchar(100) DEFAULT NULL COMMENT '负责人名称',
    `dept_id` bigint DEFAULT NULL COMMENT '部门ID',
    `contact_id` bigint DEFAULT NULL COMMENT '联系人ID',
    `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：0-停用，1-启用',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `options` text DEFAULT NULL COMMENT '扩展配置JSON',
    `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_dept` bigint DEFAULT NULL COMMENT '创建部门ID',
    `update_by` bigint DEFAULT NULL COMMENT '更新人ID',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-删除',
    PRIMARY KEY (`id`),
    KEY `idx_crm_opportunity_tenant_id` (`tenant_id`),
    KEY `idx_crm_opportunity_customer` (`tenant_id`, `customer_id`),
    KEY `idx_crm_opportunity_stage` (`tenant_id`, `stage`),
    KEY `idx_crm_opportunity_owner` (`tenant_id`, `owner_id`),
    KEY `idx_crm_opportunity_status` (`tenant_id`, `status`),
    KEY `idx_crm_opportunity_create_time` (`tenant_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM商机表';

-- 合同表
CREATE TABLE IF NOT EXISTS `crm_contract` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户编号',
    `customer_id` bigint NOT NULL COMMENT '客户ID',
    `opportunity_id` bigint DEFAULT NULL COMMENT '商机ID',
    `contract_name` varchar(200) NOT NULL COMMENT '合同名称',
    `contract_code` varchar(100) DEFAULT NULL COMMENT '合同编码',
    `contract_type` varchar(50) DEFAULT 'SALES' COMMENT '合同类型：SALES-销售，SERVICE-服务，FRAMEWORK-框架',
    `amount_cent` bigint NOT NULL DEFAULT '0' COMMENT '合同金额（分）',
    `sign_date` date DEFAULT NULL COMMENT '签约日期',
    `start_date` date DEFAULT NULL COMMENT '开始日期',
    `end_date` date DEFAULT NULL COMMENT '结束日期',
    `status` varchar(50) DEFAULT 'DRAFT' COMMENT '合同状态：DRAFT-草稿，PENDING_APPROVAL-待审批，APPROVED-已审批，EXECUTING-执行中，COMPLETED-已完成，TERMINATED-已终止',
    `approval_status` varchar(50) DEFAULT NULL COMMENT '审批状态',
    `approval_id` bigint DEFAULT NULL COMMENT '审批流程ID',
    `owner_id` bigint DEFAULT NULL COMMENT '负责人ID',
    `owner_name` varchar(100) DEFAULT NULL COMMENT '负责人名称',
    `dept_id` bigint DEFAULT NULL COMMENT '部门ID',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `options` text DEFAULT NULL COMMENT '扩展配置JSON',
    `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_dept` bigint DEFAULT NULL COMMENT '创建部门ID',
    `update_by` bigint DEFAULT NULL COMMENT '更新人ID',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-删除',
    PRIMARY KEY (`id`),
    KEY `idx_crm_contract_tenant_id` (`tenant_id`),
    KEY `idx_crm_contract_customer` (`tenant_id`, `customer_id`),
    KEY `idx_crm_contract_opportunity` (`tenant_id`, `opportunity_id`),
    KEY `idx_crm_contract_status` (`tenant_id`, `status`),
    KEY `idx_crm_contract_owner` (`tenant_id`, `owner_id`),
    KEY `idx_crm_contract_create_time` (`tenant_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM合同表';

-- 合同明细表
CREATE TABLE IF NOT EXISTS `crm_contract_item` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户编号',
    `contract_id` bigint NOT NULL COMMENT '合同ID',
    `product_name` varchar(200) NOT NULL COMMENT '产品名称',
    `product_code` varchar(100) DEFAULT NULL COMMENT '产品编码',
    `product_spec` varchar(200) DEFAULT NULL COMMENT '产品规格',
    `unit` varchar(20) DEFAULT NULL COMMENT '单位',
    `quantity` decimal(18,4) DEFAULT '0' COMMENT '数量',
    `unit_price_cent` bigint DEFAULT '0' COMMENT '单价（分）',
    `amount_cent` bigint DEFAULT '0' COMMENT '金额（分）',
    `sort_order` int DEFAULT '0' COMMENT '排序',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `options` text DEFAULT NULL COMMENT '扩展配置JSON',
    `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_dept` bigint DEFAULT NULL COMMENT '创建部门ID',
    `update_by` bigint DEFAULT NULL COMMENT '更新人ID',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-删除',
    PRIMARY KEY (`id`),
    KEY `idx_crm_contract_item_tenant_id` (`tenant_id`),
    KEY `idx_crm_contract_item_contract` (`tenant_id`, `contract_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM合同明细表';

-- 回款表
CREATE TABLE IF NOT EXISTS `crm_payment` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户编号',
    `contract_id` bigint NOT NULL COMMENT '合同ID',
    `customer_id` bigint NOT NULL COMMENT '客户ID',
    `payment_code` varchar(100) DEFAULT NULL COMMENT '回款编码',
    `amount_cent` bigint NOT NULL DEFAULT '0' COMMENT '回款金额（分）',
    `payment_date` date NOT NULL COMMENT '回款日期',
    `payment_method` varchar(50) DEFAULT 'BANK_TRANSFER' COMMENT '回款方式：BANK_TRANSFER-银行转账，CASH-现金，CHECK-支票，OTHER-其他',
    `payment_status` varchar(50) DEFAULT 'PENDING' COMMENT '回款状态：PENDING-待确认，CONFIRMED-已确认，REJECTED-已驳回',
    `receiver_id` bigint DEFAULT NULL COMMENT '收款人ID',
    `receiver_name` varchar(100) DEFAULT NULL COMMENT '收款人名称',
    `invoice_no` varchar(100) DEFAULT NULL COMMENT '发票号',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `options` text DEFAULT NULL COMMENT '扩展配置JSON',
    `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_dept` bigint DEFAULT NULL COMMENT '创建部门ID',
    `update_by` bigint DEFAULT NULL COMMENT '更新人ID',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-删除',
    PRIMARY KEY (`id`),
    KEY `idx_crm_payment_tenant_id` (`tenant_id`),
    KEY `idx_crm_payment_contract` (`tenant_id`, `contract_id`),
    KEY `idx_crm_payment_customer` (`tenant_id`, `customer_id`),
    KEY `idx_crm_payment_status` (`tenant_id`, `payment_status`),
    KEY `idx_crm_payment_date` (`tenant_id`, `payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM回款表';

-- 跟进记录表
CREATE TABLE IF NOT EXISTS `crm_follow_record` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户编号',
    `customer_id` bigint NOT NULL COMMENT '客户ID',
    `opportunity_id` bigint DEFAULT NULL COMMENT '商机ID',
    `contact_id` bigint DEFAULT NULL COMMENT '联系人ID',
    `follow_type` varchar(50) DEFAULT 'VISIT' COMMENT '跟进方式：VISIT-拜访，PHONE-电话，EMAIL-邮件，WECHAT-微信，OTHER-其他',
    `follow_content` text NOT NULL COMMENT '跟进内容',
    `follow_time` datetime NOT NULL COMMENT '跟进时间',
    `next_follow_time` datetime DEFAULT NULL COMMENT '下次跟进时间',
    `next_follow_content` varchar(500) DEFAULT NULL COMMENT '下次跟进内容',
    `follow_user_id` bigint DEFAULT NULL COMMENT '跟进人ID',
    `follow_user_name` varchar(100) DEFAULT NULL COMMENT '跟进人名称',
    `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：0-停用，1-启用',
    `options` text DEFAULT NULL COMMENT '扩展配置JSON',
    `create_by` bigint DEFAULT NULL COMMENT '创建人ID',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_dept` bigint DEFAULT NULL COMMENT '创建部门ID',
    `update_by` bigint DEFAULT NULL COMMENT '更新人ID',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记：0-正常，1-删除',
    PRIMARY KEY (`id`),
    KEY `idx_crm_follow_record_tenant_id` (`tenant_id`),
    KEY `idx_crm_follow_record_customer` (`tenant_id`, `customer_id`),
    KEY `idx_crm_follow_record_opportunity` (`tenant_id`, `opportunity_id`),
    KEY `idx_crm_follow_record_contact` (`tenant_id`, `contact_id`),
    KEY `idx_crm_follow_record_time` (`tenant_id`, `follow_time`),
    KEY `idx_crm_follow_record_user` (`tenant_id`, `follow_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM跟进记录表';
