-- CRM 核心对象运行配置初始化
-- 为 CRM 客户、联系人、商机、合同、回款创建运行配置

-- 客户运行配置
INSERT INTO `ai_crud_config` (`id`, `tenant_id`, `config_key`, `table_name`, `table_comment`, `app_name`, `mode`, `build_mode`, `status`, `publish_status`, `object_code`, `object_name`, `domain_code`, `search_schema`, `columns_schema`, `edit_schema`, `api_config`, `options`, `model_schema`, `create_by`, `create_time`, `update_by`, `update_time`)
SELECT 2001, 1, 'crm_customer', 'crm_customer', 'CRM客户表', '客户管理', 'CONFIG', 'LOWCODE', 1, 'PUBLISHED', 'customer', '客户', 'CRM',
    '[{"field":"customer_name","label":"客户名称","type":"input","props":{"placeholder":"请输入客户名称"}},{"field":"customer_type","label":"客户类型","type":"select","props":{"options":[{"label":"企业","value":"ENTERPRISE"},{"label":"个人","value":"PERSONAL"}]}},{"field":"status","label":"状态","type":"select","props":{"options":[{"label":"启用","value":1},{"label":"停用","value":0}]}}]',
    '[{"prop":"customer_name","label":"客户名称","width":150},{"prop":"customer_code","label":"客户编码","width":120},{"prop":"customer_type","label":"客户类型","width":100},{"prop":"contact_name","label":"联系人","width":100},{"prop":"contact_phone","label":"联系电话","width":120},{"prop":"level","label":"客户等级","width":80},{"prop":"status","label":"状态","width":80},{"prop":"create_time","label":"创建时间","width":160}]',
    '[{"field":"customer_name","label":"客户名称","type":"input","rules":[{"required":true,"message":"请输入客户名称"}],"props":{"placeholder":"请输入客户名称"}},{"field":"customer_code","label":"客户编码","type":"input","props":{"placeholder":"请输入客户编码"}},{"field":"customer_type","label":"客户类型","type":"select","defaultValue":"ENTERPRISE","props":{"options":[{"label":"企业","value":"ENTERPRISE"},{"label":"个人","value":"PERSONAL"}]}},{"field":"industry","label":"所属行业","type":"input","props":{"placeholder":"请输入所属行业"}},{"field":"contact_name","label":"联系人","type":"input","props":{"placeholder":"请输入联系人"}},{"field":"contact_phone","label":"联系电话","type":"input","props":{"placeholder":"请输入联系电话"}},{"field":"contact_email","label":"联系邮箱","type":"input","props":{"placeholder":"请输入联系邮箱"}},{"field":"level","label":"客户等级","type":"select","defaultValue":"NORMAL","props":{"options":[{"label":"重要","value":"VIP"},{"label":"普通","value":"NORMAL"},{"label":"潜在","value":"POTENTIAL"}]}},{"field":"status","label":"状态","type":"switch","defaultValue":1,"props":{"checkedValue":1,"uncheckedValue":0}},{"field":"remark","label":"备注","type":"textarea","props":{"placeholder":"请输入备注"}}]',
    '{"list":"get@/ai/crud/crm_customer/page","detail":"get@/ai/crud/crm_customer/:id","add":"post@/ai/crud/crm_customer","update":"put@/ai/crud/crm_customer","delete":"delete@/ai/crud/crm_customer/:id","importTemplate":"get@/ai/crud/crm_customer/import-template","import":"post@/ai/crud/crm_customer/import","export":"post@/ai/crud/crm_customer/export"}',
    '{"importEnabled":true,"exportEnabled":true,"detailEnabled":true}',
    '{"fields":[{"name":"id","type":"bigint","primaryKey":true,"autoIncrement":true},{"name":"customer_name","type":"varchar","length":200,"required":true},{"name":"customer_code","type":"varchar","length":100},{"name":"customer_type","type":"varchar","length":50,"defaultValue":"ENTERPRISE"},{"name":"industry","type":"varchar","length":100},{"name":"contact_name","type":"varchar","length":100},{"name":"contact_phone","type":"varchar","length":50},{"name":"contact_email","type":"varchar","length":200},{"name":"level","type":"varchar","length":20,"defaultValue":"NORMAL"},{"name":"status","type":"tinyint","defaultValue":1},{"name":"remark","type":"varchar","length":500}]}',
    NULL, NOW(), NULL, NOW()
WHERE NOT EXISTS (SELECT 1 FROM `ai_crud_config` WHERE `tenant_id` = 1 AND `config_key` = 'crm_customer');

-- 联系人运行配置
INSERT INTO `ai_crud_config` (`id`, `tenant_id`, `config_key`, `table_name`, `table_comment`, `app_name`, `mode`, `build_mode`, `status`, `publish_status`, `object_code`, `object_name`, `domain_code`, `search_schema`, `columns_schema`, `edit_schema`, `api_config`, `options`, `model_schema`, `create_by`, `create_time`, `update_by`, `update_time`)
SELECT 2002, 1, 'crm_contact', 'crm_contact', 'CRM联系人表', '联系人管理', 'CONFIG', 'LOWCODE', 1, 'PUBLISHED', 'contact', '联系人', 'CRM',
    '[{"field":"contact_name","label":"联系人姓名","type":"input","props":{"placeholder":"请输入联系人姓名"}},{"field":"phone","label":"手机号码","type":"input","props":{"placeholder":"请输入手机号码"}},{"field":"customer_id","label":"客户","type":"input","props":{"placeholder":"请输入客户名称"}}]',
    '[{"prop":"contact_name","label":"联系人姓名","width":120},{"prop":"customer_name","label":"所属客户","width":150},{"prop":"position","label":"职位","width":100},{"prop":"phone","label":"手机号码","width":120},{"prop":"email","label":"邮箱","width":150},{"prop":"is_primary","label":"主联系人","width":80},{"prop":"status","label":"状态","width":80},{"prop":"create_time","label":"创建时间","width":160}]',
    '[{"field":"customer_id","label":"所属客户","type":"input","rules":[{"required":true,"message":"请选择所属客户"}],"props":{"placeholder":"请选择所属客户"}},{"field":"contact_name","label":"联系人姓名","type":"input","rules":[{"required":true,"message":"请输入联系人姓名"}],"props":{"placeholder":"请输入联系人姓名"}},{"field":"gender","label":"性别","type":"select","props":{"options":[{"label":"男","value":1},{"label":"女","value":0}]}},{"field":"position","label":"职位","type":"input","props":{"placeholder":"请输入职位"}},{"field":"phone","label":"手机号码","type":"input","props":{"placeholder":"请输入手机号码"}},{"field":"email","label":"邮箱","type":"input","props":{"placeholder":"请输入邮箱"}},{"field":"wechat","label":"微信号","type":"input","props":{"placeholder":"请输入微信号"}},{"field":"is_primary","label":"主联系人","type":"switch","defaultValue":0,"props":{"checkedValue":1,"uncheckedValue":0}},{"field":"status","label":"状态","type":"switch","defaultValue":1,"props":{"checkedValue":1,"uncheckedValue":0}},{"field":"remark","label":"备注","type":"textarea","props":{"placeholder":"请输入备注"}}]',
    '{"list":"get@/ai/crud/crm_contact/page","detail":"get@/ai/crud/crm_contact/:id","add":"post@/ai/crud/crm_contact","update":"put@/ai/crud/crm_contact","delete":"delete@/ai/crud/crm_contact/:id","importTemplate":"get@/ai/crud/crm_contact/import-template","import":"post@/ai/crud/crm_contact/import","export":"post@/ai/crud/crm_contact/export"}',
    '{"importEnabled":true,"exportEnabled":true,"detailEnabled":true}',
    '{"fields":[{"name":"id","type":"bigint","primaryKey":true,"autoIncrement":true},{"name":"customer_id","type":"bigint","required":true},{"name":"contact_name","type":"varchar","length":100,"required":true},{"name":"gender","type":"tinyint"},{"name":"position","type":"varchar","length":100},{"name":"phone","type":"varchar","length":50},{"name":"email","type":"varchar","length":200},{"name":"wechat","type":"varchar","length":100},{"name":"is_primary","type":"tinyint","defaultValue":0},{"name":"status","type":"tinyint","defaultValue":1},{"name":"remark","type":"varchar","length":500}]}',
    NULL, NOW(), NULL, NOW()
WHERE NOT EXISTS (SELECT 1 FROM `ai_crud_config` WHERE `tenant_id` = 1 AND `config_key` = 'crm_contact');

-- 商机运行配置
INSERT INTO `ai_crud_config` (`id`, `tenant_id`, `config_key`, `table_name`, `table_comment`, `app_name`, `mode`, `build_mode`, `status`, `publish_status`, `object_code`, `object_name`, `domain_code`, `search_schema`, `columns_schema`, `edit_schema`, `api_config`, `options`, `model_schema`, `create_by`, `create_time`, `update_by`, `update_time`)
SELECT 2003, 1, 'crm_opportunity', 'crm_opportunity', 'CRM商机表', '商机管理', 'CONFIG', 'LOWCODE', 1, 'PUBLISHED', 'opportunity', '商机', 'CRM',
    '[{"field":"opportunity_name","label":"商机名称","type":"input","props":{"placeholder":"请输入商机名称"}},{"field":"stage","label":"商机阶段","type":"select","props":{"options":[{"label":"初步接触","value":"INITIAL"},{"label":"跟进中","value":"FOLLOWING"},{"label":"商务谈判","value":"NEGOTIATION"},{"label":"赢单","value":"CLOSED_WON"},{"label":"丢单","value":"CLOSED_LOST"}]}},{"field":"customer_id","label":"客户","type":"input","props":{"placeholder":"请输入客户名称"}}]',
    '[{"prop":"opportunity_name","label":"商机名称","width":200},{"prop":"customer_name","label":"所属客户","width":150},{"prop":"stage","label":"商机阶段","width":100},{"prop":"amount_cent","label":"预计金额","width":120},{"prop":"probability","label":"赢单概率","width":80},{"prop":"expected_close_date","label":"预计成交日期","width":120},{"prop":"owner_name","label":"负责人","width":100},{"prop":"status","label":"状态","width":80},{"prop":"create_time","label":"创建时间","width":160}]',
    '[{"field":"customer_id","label":"所属客户","type":"input","rules":[{"required":true,"message":"请选择所属客户"}],"props":{"placeholder":"请选择所属客户"}},{"field":"opportunity_name","label":"商机名称","type":"input","rules":[{"required":true,"message":"请输入商机名称"}],"props":{"placeholder":"请输入商机名称"}},{"field":"stage","label":"商机阶段","type":"select","defaultValue":"INITIAL","props":{"options":[{"label":"初步接触","value":"INITIAL"},{"label":"跟进中","value":"FOLLOWING"},{"label":"商务谈判","value":"NEGOTIATION"},{"label":"赢单","value":"CLOSED_WON"},{"label":"丢单","value":"CLOSED_LOST"}]}},{"field":"amount_cent","label":"预计金额（分）","type":"input-number","props":{"placeholder":"请输入预计金额","min":0}},{"field":"probability","label":"赢单概率","type":"input-number","props":{"placeholder":"请输入赢单概率","min":0,"max":100}},{"field":"expected_close_date","label":"预计成交日期","type":"date","props":{"placeholder":"请选择预计成交日期"}},{"field":"status","label":"状态","type":"switch","defaultValue":1,"props":{"checkedValue":1,"uncheckedValue":0}},{"field":"remark","label":"备注","type":"textarea","props":{"placeholder":"请输入备注"}}]',
    '{"list":"get@/ai/crud/crm_opportunity/page","detail":"get@/ai/crud/crm_opportunity/:id","add":"post@/ai/crud/crm_opportunity","update":"put@/ai/crud/crm_opportunity","delete":"delete@/ai/crud/crm_opportunity/:id","importTemplate":"get@/ai/crud/crm_opportunity/import-template","import":"post@/ai/crud/crm_opportunity/import","export":"post@/ai/crud/crm_opportunity/export"}',
    '{"importEnabled":true,"exportEnabled":true,"detailEnabled":true}',
    '{"fields":[{"name":"id","type":"bigint","primaryKey":true,"autoIncrement":true},{"name":"customer_id","type":"bigint","required":true},{"name":"opportunity_name","type":"varchar","length":200,"required":true},{"name":"stage","type":"varchar","length":50,"defaultValue":"INITIAL"},{"name":"amount_cent","type":"bigint","defaultValue":0},{"name":"probability","type":"int","defaultValue":0},{"name":"expected_close_date","type":"date"},{"name":"owner_id","type":"bigint"},{"name":"owner_name","type":"varchar","length":100},{"name":"status","type":"tinyint","defaultValue":1},{"name":"remark","type":"varchar","length":500}]}',
    NULL, NOW(), NULL, NOW()
WHERE NOT EXISTS (SELECT 1 FROM `ai_crud_config` WHERE `tenant_id` = 1 AND `config_key` = 'crm_opportunity');

-- 合同运行配置
INSERT INTO `ai_crud_config` (`id`, `tenant_id`, `config_key`, `table_name`, `table_comment`, `app_name`, `mode`, `build_mode`, `status`, `publish_status`, `object_code`, `object_name`, `domain_code`, `search_schema`, `columns_schema`, `edit_schema`, `api_config`, `options`, `model_schema`, `create_by`, `create_time`, `update_by`, `update_time`)
SELECT 2004, 1, 'crm_contract', 'crm_contract', 'CRM合同表', '合同管理', 'CONFIG', 'LOWCODE', 1, 'PUBLISHED', 'contract', '合同', 'CRM',
    '[{"field":"contract_name","label":"合同名称","type":"input","props":{"placeholder":"请输入合同名称"}},{"field":"contract_code","label":"合同编码","type":"input","props":{"placeholder":"请输入合同编码"}},{"field":"status","label":"合同状态","type":"select","props":{"options":[{"label":"草稿","value":"DRAFT"},{"label":"待审批","value":"PENDING_APPROVAL"},{"label":"已审批","value":"APPROVED"},{"label":"执行中","value":"EXECUTING"},{"label":"已完成","value":"COMPLETED"},{"label":"已终止","value":"TERMINATED"}]}},{"field":"customer_id","label":"客户","type":"input","props":{"placeholder":"请输入客户名称"}}]',
    '[{"prop":"contract_name","label":"合同名称","width":200},{"prop":"contract_code","label":"合同编码","width":120},{"prop":"customer_name","label":"所属客户","width":150},{"prop":"amount_cent","label":"合同金额","width":120},{"prop":"status","label":"合同状态","width":100},{"prop":"sign_date","label":"签约日期","width":120},{"prop":"owner_name","label":"负责人","width":100},{"prop":"create_time","label":"创建时间","width":160}]',
    '[{"field":"customer_id","label":"所属客户","type":"input","rules":[{"required":true,"message":"请选择所属客户"}],"props":{"placeholder":"请选择所属客户"}},{"field":"opportunity_id","label":"关联商机","type":"input","props":{"placeholder":"请选择关联商机"}},{"field":"contract_name","label":"合同名称","type":"input","rules":[{"required":true,"message":"请输入合同名称"}],"props":{"placeholder":"请输入合同名称"}},{"field":"contract_code","label":"合同编码","type":"input","props":{"placeholder":"请输入合同编码"}},{"field":"contract_type","label":"合同类型","type":"select","defaultValue":"SALES","props":{"options":[{"label":"销售","value":"SALES"},{"label":"服务","value":"SERVICE"},{"label":"框架","value":"FRAMEWORK"}]}},{"field":"amount_cent","label":"合同金额（分）","type":"input-number","rules":[{"required":true,"message":"请输入合同金额"}],"props":{"placeholder":"请输入合同金额","min":0}},{"field":"sign_date","label":"签约日期","type":"date","props":{"placeholder":"请选择签约日期"}},{"field":"start_date","label":"开始日期","type":"date","props":{"placeholder":"请选择开始日期"}},{"field":"end_date","label":"结束日期","type":"date","props":{"placeholder":"请选择结束日期"}},{"field":"status","label":"合同状态","type":"select","defaultValue":"DRAFT","props":{"options":[{"label":"草稿","value":"DRAFT"},{"label":"待审批","value":"PENDING_APPROVAL"},{"label":"已审批","value":"APPROVED"},{"label":"执行中","value":"EXECUTING"},{"label":"已完成","value":"COMPLETED"},{"label":"已终止","value":"TERMINATED"}]}},{"field":"remark","label":"备注","type":"textarea","props":{"placeholder":"请输入备注"}}]',
    '{"list":"get@/ai/crud/crm_contract/page","detail":"get@/ai/crud/crm_contract/:id","add":"post@/ai/crud/crm_contract","update":"put@/ai/crud/crm_contract","delete":"delete@/ai/crud/crm_contract/:id","importTemplate":"get@/ai/crud/crm_contract/import-template","import":"post@/ai/crud/crm_contract/import","export":"post@/ai/crud/crm_contract/export"}',
    '{"importEnabled":true,"exportEnabled":true,"detailEnabled":true}',
    '{"fields":[{"name":"id","type":"bigint","primaryKey":true,"autoIncrement":true},{"name":"customer_id","type":"bigint","required":true},{"name":"opportunity_id","type":"bigint"},{"name":"contract_name","type":"varchar","length":200,"required":true},{"name":"contract_code","type":"varchar","length":100},{"name":"contract_type","type":"varchar","length":50,"defaultValue":"SALES"},{"name":"amount_cent","type":"bigint","required":true},{"name":"sign_date","type":"date"},{"name":"start_date","type":"date"},{"name":"end_date","type":"date"},{"name":"status","type":"varchar","length":50,"defaultValue":"DRAFT"},{"name":"owner_id","type":"bigint"},{"name":"owner_name","type":"varchar","length":100},{"name":"remark","type":"varchar","length":500}]}',
    NULL, NOW(), NULL, NOW()
WHERE NOT EXISTS (SELECT 1 FROM `ai_crud_config` WHERE `tenant_id` = 1 AND `config_key` = 'crm_contract');

-- 回款运行配置
INSERT INTO `ai_crud_config` (`id`, `tenant_id`, `config_key`, `table_name`, `table_comment`, `app_name`, `mode`, `build_mode`, `status`, `publish_status`, `object_code`, `object_name`, `domain_code`, `search_schema`, `columns_schema`, `edit_schema`, `api_config`, `options`, `model_schema`, `create_by`, `create_time`, `update_by`, `update_time`)
SELECT 2005, 1, 'crm_payment', 'crm_payment', 'CRM回款表', '回款管理', 'CONFIG', 'LOWCODE', 1, 'PUBLISHED', 'payment', '回款', 'CRM',
    '[{"field":"contract_id","label":"合同","type":"input","props":{"placeholder":"请输入合同名称"}},{"field":"customer_id","label":"客户","type":"input","props":{"placeholder":"请输入客户名称"}},{"field":"payment_status","label":"回款状态","type":"select","props":{"options":[{"label":"待确认","value":"PENDING"},{"label":"已确认","value":"CONFIRMED"},{"label":"已驳回","value":"REJECTED"}]}}]',
    '[{"prop":"contract_name","label":"所属合同","width":200},{"prop":"customer_name","label":"所属客户","width":150},{"prop":"amount_cent","label":"回款金额","width":120},{"prop":"payment_date","label":"回款日期","width":120},{"prop":"payment_method","label":"回款方式","width":100},{"prop":"payment_status","label":"回款状态","width":100},{"prop":"receiver_name","label":"收款人","width":100},{"prop":"create_time","label":"创建时间","width":160}]',
    '[{"field":"contract_id","label":"所属合同","type":"input","rules":[{"required":true,"message":"请选择所属合同"}],"props":{"placeholder":"请选择所属合同"}},{"field":"customer_id","label":"所属客户","type":"input","rules":[{"required":true,"message":"请选择所属客户"}],"props":{"placeholder":"请选择所属客户"}},{"field":"amount_cent","label":"回款金额（分）","type":"input-number","rules":[{"required":true,"message":"请输入回款金额"}],"props":{"placeholder":"请输入回款金额","min":0}},{"field":"payment_date","label":"回款日期","type":"date","rules":[{"required":true,"message":"请选择回款日期"}],"props":{"placeholder":"请选择回款日期"}},{"field":"payment_method","label":"回款方式","type":"select","defaultValue":"BANK_TRANSFER","props":{"options":[{"label":"银行转账","value":"BANK_TRANSFER"},{"label":"现金","value":"CASH"},{"label":"支票","value":"CHECK"},{"label":"其他","value":"OTHER"}]}},{"field":"payment_status","label":"回款状态","type":"select","defaultValue":"PENDING","props":{"options":[{"label":"待确认","value":"PENDING"},{"label":"已确认","value":"CONFIRMED"},{"label":"已驳回","value":"REJECTED"}]}},{"field":"invoice_no","label":"发票号","type":"input","props":{"placeholder":"请输入发票号"}},{"field":"remark","label":"备注","type":"textarea","props":{"placeholder":"请输入备注"}}]',
    '{"list":"get@/ai/crud/crm_payment/page","detail":"get@/ai/crud/crm_payment/:id","add":"post@/ai/crud/crm_payment","update":"put@/ai/crud/crm_payment","delete":"delete@/ai/crud/crm_payment/:id","importTemplate":"get@/ai/crud/crm_payment/import-template","import":"post@/ai/crud/crm_payment/import","export":"post@/ai/crud/crm_payment/export"}',
    '{"importEnabled":true,"exportEnabled":true,"detailEnabled":true}',
    '{"fields":[{"name":"id","type":"bigint","primaryKey":true,"autoIncrement":true},{"name":"contract_id","type":"bigint","required":true},{"name":"customer_id","type":"bigint","required":true},{"name":"amount_cent","type":"bigint","required":true},{"name":"payment_date","type":"date","required":true},{"name":"payment_method","type":"varchar","length":50,"defaultValue":"BANK_TRANSFER"},{"name":"payment_status","type":"varchar","length":50,"defaultValue":"PENDING"},{"name":"receiver_id","type":"bigint"},{"name":"receiver_name","type":"varchar","length":100},{"name":"invoice_no","type":"varchar","length":100},{"name":"remark","type":"varchar","length":500}]}',
    NULL, NOW(), NULL, NOW()
WHERE NOT EXISTS (SELECT 1 FROM `ai_crud_config` WHERE `tenant_id` = 1 AND `config_key` = 'crm_payment');
