import { request } from '@/utils'

export default {
  getPublicKey: () => request({ url: '/crypto/public-key', method: 'get', needToken: false }),
  getLoginConfig: params => request({ url: '/auth/loginConfig', method: 'get', params, needToken: false }),
  getCaptcha: () => request({ url: '/auth/captcha', method: 'get', needToken: false }),
  login: data => request({ url: '/auth/login', method: 'post', data, needToken: false, needTip: false }),
  getWecomAuthorize: (params = {}) => request({
    url: '/collaboration/login/authorize',
    method: 'get',
    params,
    needToken: false,
    needTip: false,
  }),
  wecomLoginCallback: data => request({
    url: '/collaboration/login/callback',
    method: 'post',
    data,
    needToken: false,
    needTip: false,
  }),
  getWecomSsoConnection: (params = {}) => request({
    url: '/collaboration/login/sso-connection',
    method: 'get',
    params,
    needToken: false,
    needTip: false,
  }),
  logout: () => request({ url: '/auth/logout', method: 'post', needTip: false }),
  getUserInfo: () => request({ url: '/auth/userInfo', method: 'get' }),
  getCurrentMenu: () => request({ url: '/auth/current/menu', method: 'get' }),
  getCurrentPermissions: () => request({ url: '/auth/current/permissions', method: 'get' }),
  updateUserProfile: data => request({
    url: '/system/user/updateProfile',
    method: 'post',
    data,
    encrypt: true,
  }),
  changePassword: data => request({
    url: '/auth/changePassword',
    method: 'post',
    params: {
      oldPassword: data?.oldPassword,
      newPassword: data?.newPassword,
    },
  }),
  getTodoTasks: (params = {}) => request({
    url: '/api/flow/task/todo',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  getDoneFlowTasks: (params = {}) => request({
    url: '/api/flow/task/done',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  getStartedFlowTasks: (params = {}) => request({
    url: '/api/flow/task/started',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  getFlowTaskDetail: taskId => request({
    url: `/api/flow/task/${taskId}`,
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  getFlowTaskForm: taskId => request({
    url: `/api/flow/task/form/${taskId}`,
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  getFlowProcessForm: (params = {}) => request({
    url: '/api/flow/task/form',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  getFlowTaskHistory: processInstanceId => request({
    url: `/api/flow/task/history/${processInstanceId}`,
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  getFlowDiagramInfo: (processInstanceId, params = {}) => request({
    url: `/api/flow/task/diagram-info/${processInstanceId}`,
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  approveFlowTask: data => request({
    url: '/api/flow/task/approve',
    method: 'post',
    data,
    encrypt: true,
  }),
  rejectFlowTask: data => request({
    url: '/api/flow/task/reject',
    method: 'post',
    data,
    encrypt: true,
  }),
  claimFlowTask: (taskId, userId) => request({
    url: '/api/flow/task/claim',
    method: 'post',
    params: { taskId, userId },
    encrypt: true,
  }),
  returnFlowTask: data => request({
    url: '/api/flow/task/return',
    method: 'post',
    data,
    encrypt: true,
  }),
  terminateFlowTask: data => request({
    url: '/api/flow/task/terminate',
    method: 'post',
    data,
    encrypt: true,
  }),
  delegateFlowTask: data => request({
    url: '/api/flow/task/delegate',
    method: 'post',
    data,
    encrypt: true,
  }),
  withdrawFlowProcess: data => request({
    url: '/api/flow/task/withdraw',
    method: 'post',
    data,
    encrypt: true,
  }),
  getFlowCategories: () => request({
    url: '/api/flow/category/enabled',
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  listUsableCommentPhrases: (params = {}) => request({
    url: '/api/flow/comment-phrases/usable',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  createCommentPhrase: data => request({
    url: '/api/flow/comment-phrases',
    method: 'post',
    data,
    encrypt: true,
  }),
  getUserPage: (params = {}) => request({
    url: '/system/user/page',
    method: 'get',
    params,
    needTip: false,
  }),
  getBusinessTaskFormContext: (params = {}) => request({
    url: '/ai/business/flow/task-form-context',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  getBusinessTaskReadonlyContext: (params = {}) => request({
    url: '/ai/business/flow/task-form-context/readonly',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  saveBusinessTaskFormContext: data => request({
    url: '/ai/business/flow/task-form-context',
    method: 'put',
    data,
    encrypt: true,
  }),
  completeBusinessTaskAction: data => request({
    url: '/ai/business/flow/task-action',
    method: 'post',
    data,
    encrypt: true,
  }),
  getMessagePage: (params = {}) => {
    const {
      pageNum = 1,
      pageSize = 10,
      ...query
    } = params || {}
    return request({
      url: '/api/message/page',
      method: 'post',
      params: { pageNum, pageSize },
      data: query,
      encrypt: true,
      needTip: false,
    })
  },
  getMessageDetail: id => request({
    url: `/api/message/${id}`,
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  getUnreadMessageCount: () => request({
    url: '/api/message/unread/count',
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  markMessageRead: id => request({
    url: `/api/message/${id}/read`,
    method: 'post',
    data: {},
    encrypt: true,
    needTip: false,
  }),
  markAllMessagesRead: () => request({
    url: '/api/message/read/all',
    method: 'post',
    data: {},
    encrypt: true,
    needTip: false,
  }),
  getEnabledMessageBizTypes: () => request({
    url: '/api/message/bizType/list/enabled',
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  getTenantConfig: tenantId => request({
    url: '/system/tenant/userTenantConfig',
    method: 'post',
    data: { id: tenantId },
  }),
  getCurrentTenantOptions: () => request({
    url: '/system/tenant/current/options',
    method: 'get',
  }),
  switchTenant: tenantId => request({
    url: '/system/tenant/switch',
    method: 'post',
    params: { tenantId },
  }),

  // 通用低代码运行时。H5 与管理端共用发布态协议和动态 CRUD，后端由 app-server 暴露同一套运行接口。
  getLowcodeRenderConfig: (configKey, params = {}) => request({
    url: `/ai/crud-config/render/${encodeURIComponent(configKey)}`,
    method: 'get',
    params,
    needTip: false,
  }),
  getLowcodePage: (configKey, params = {}) => request({
    url: `/ai/crud/${encodeURIComponent(configKey)}/page`,
    method: 'get',
    params,
    needTip: false,
  }),
  getLowcodeDetail: (configKey, id) => request({
    url: `/ai/crud/${encodeURIComponent(configKey)}/${encodeURIComponent(id)}`,
    method: 'get',
    needTip: false,
  }),
  createLowcodeRecord: (configKey, data) => request({
    url: `/ai/crud/${encodeURIComponent(configKey)}`,
    method: 'post',
    data,
    encrypt: true,
  }),
  updateLowcodeRecord: (configKey, data) => request({
    url: `/ai/crud/${encodeURIComponent(configKey)}`,
    method: 'put',
    data,
    encrypt: true,
  }),
  deleteLowcodeRecord: (configKey, id) => request({
    url: `/ai/crud/${encodeURIComponent(configKey)}/${encodeURIComponent(id)}`,
    method: 'delete',
    needTip: false,
  }),
  getDictOptions: dictType => request({
    url: `/system/dict/data/type/${encodeURIComponent(dictType)}`,
    method: 'get',
    needTip: false,
  }),
  executeLowcodeQuerySource: (data, options = {}) => request({
    ...options,
    url: '/ai/lowcode/query-source/execute',
    method: 'post',
    data,
    encrypt: true,
    needTip: false,
  }),
  executeBusinessAction: data => request({
    url: '/ai/business/action/execute',
    method: 'post',
    data,
    encrypt: true,
  }),
}
