import { request } from '@/utils'

export default {
  getPublicKey: () => request({ url: '/crypto/public-key', method: 'get', needToken: false }),
  getLoginConfig: params => request({ url: '/auth/loginConfig', method: 'get', params, needToken: false }),
  getCaptcha: () => request({ url: '/auth/captcha', method: 'get', needToken: false }),
  login: data => request({ url: '/auth/login', method: 'post', data, needToken: false, needTip: false }),
  getWecomAuthorize: (params = {}) => request({
    url: '/collaboration/login/authorize',
    method: 'get',
    params,
    needToken: false,
    needTip: false,
  }),
  wecomLoginCallback: data => request({
    url: '/collaboration/login/callback',
    method: 'post',
    data,
    needToken: false,
    needTip: false,
  }),
  getWecomSsoConnection: (params = {}) => request({
    url: '/collaboration/login/sso-connection',
    method: 'get',
    params,
    needToken: false,
    needTip: false,
  }),
  logout: () => request({ url: '/auth/logout', method: 'post', needTip: false }),
  getUserInfo: () => request({ url: '/auth/userInfo', method: 'get' }),
  getCurrentMenu: () => request({ url: '/auth/current/menu', method: 'get' }),
  getCurrentPermissions: () => request({ url: '/auth/current/permissions', method: 'get' }),
  updateUserProfile: data => request({
    url: '/system/user/updateProfile',
    method: 'post',
    data,
    encrypt: true,
  }),
  changePassword: data => request({
    url: '/auth/changePassword',
    method: 'post',
    params: {
      oldPassword: data?.oldPassword,
      newPassword: data?.newPassword,
    },
  }),
  getTodoTasks: (params = {}) => request({
    url: '/api/flow/task/todo',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  getDoneFlowTasks: (params = {}) => request({
    url: '/api/flow/task/done',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  getStartedFlowTasks: (params = {}) => request({
    url: '/api/flow/task/started',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  getFlowTaskDetail: taskId => request({
    url: `/api/flow/task/${taskId}`,
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  getFlowTaskForm: taskId => request({
    url: `/api/flow/task/form/${taskId}`,
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  getFlowProcessForm: (params = {}) => request({
    url: '/api/flow/task/form',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  getFlowTaskHistory: processInstanceId => request({
    url: `/api/flow/task/history/${processInstanceId}`,
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  getFlowDiagramInfo: (processInstanceId, params = {}) => request({
    url: `/api/flow/task/diagram-info/${processInstanceId}`,
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  approveFlowTask: data => request({
    url: '/api/flow/task/approve',
    method: 'post',
    data,
    encrypt: true,
  }),
  rejectFlowTask: data => request({
    url: '/api/flow/task/reject',
    method: 'post',
    data,
    encrypt: true,
  }),
  rejectToStartFlowTask: data => request({
    url: '/api/flow/task/reject-to-start',
    method: 'post',
    data,
    encrypt: true,
  }),
  claimFlowTask: (taskId, userId) => request({
    url: '/api/flow/task/claim',
    method: 'post',
    params: { taskId, userId },
    encrypt: true,
  }),
  returnFlowTask: data => request({
    url: '/api/flow/task/return',
    method: 'post',
    data,
    encrypt: true,
  }),
  terminateFlowTask: data => request({
    url: '/api/flow/task/terminate',
    method: 'post',
    data,
    encrypt: true,
  }),
  delegateFlowTask: data => request({
    url: '/api/flow/task/delegate',
    method: 'post',
    data,
    encrypt: true,
  }),
  withdrawFlowProcess: data => request({
    url: '/api/flow/task/withdraw',
    method: 'post',
    data,
    encrypt: true,
  }),
  remindFlowTask: taskId => request({
    url: '/api/flow/task/remind',
    method: 'post',
    params: { taskId },
    encrypt: true,
    needTip: false,
  }),
  addFlowTaskSign: data => request({
    url: '/api/flow/task/add-sign',
    method: 'post',
    data,
    encrypt: true,
    needTip: false,
  }),
  reduceFlowTaskSign: data => request({
    url: '/api/flow/task/reduce-sign',
    method: 'post',
    data,
    encrypt: true,
    needTip: false,
  }),
  getFlowTaskSignRelations: (taskId, userId) => request({
    url: `/api/flow/task/${encodeURIComponent(String(taskId || ''))}/sign-relations`,
    method: 'get',
    params: { userId },
    encrypt: true,
    needTip: false,
  }),
  getMyCcPage: (params = {}) => request({
    url: '/api/flow/cc/my',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  getCcUnreadCount: () => request({
    url: '/api/flow/cc/unread/count',
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  getCcFormInfo: id => request({
    url: `/api/flow/cc/form/${encodeURIComponent(String(id || ''))}`,
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  markCcRead: id => request({
    url: `/api/flow/cc/read/${encodeURIComponent(String(id || ''))}`,
    method: 'post',
    encrypt: true,
    needTip: false,
  }),
  markAllCcRead: () => request({
    url: '/api/flow/cc/read/all',
    method: 'post',
    encrypt: true,
    needTip: false,
  }),
  getFlowCategories: () => request({
    url: '/api/flow/category/enabled',
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  listUsableCommentPhrases: (params = {}) => request({
    url: '/api/flow/comment-phrases/usable',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  listMyCommentPhrases: () => request({
    url: '/api/flow/comment-phrases/mine',
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  createCommentPhrase: data => request({
    url: '/api/flow/comment-phrases',
    method: 'post',
    data,
    encrypt: true,
  }),
  deleteCommentPhrase: id => request({
    url: `/api/flow/comment-phrases/${encodeURIComponent(String(id || ''))}`,
    method: 'delete',
    encrypt: true,
  }),
  getUserPage: (params = {}) => request({
    url: '/system/user/page',
    method: 'get',
    params,
    needTip: false,
  }),
  getOrgTree: (params = {}) => request({
    url: '/system/org/tree',
    method: 'get',
    params,
    needTip: false,
  }),
  getContactsSummary: () => request({
    url: '/system/contacts/summary',
    method: 'get',
    needTip: false,
  }),
  getContactOrgs: (parentId) => request({
    url: '/system/contacts/orgs',
    method: 'get',
    params: parentId ? { parentId } : {},
    needTip: false,
  }),
  getContactMembers: (params = {}) => request({
    url: '/system/contacts/members',
    method: 'get',
    params,
    needTip: false,
  }),
  getContactMember: userId => request({
    url: `/system/contacts/members/${encodeURIComponent(String(userId || ''))}`,
    method: 'get',
    needTip: false,
  }),
  getRegionTree: (params = {}) => request({
    url: '/system/region/treeAll',
    method: 'get',
    params,
    needTip: false,
  }),
  getBusinessTaskFormContext: (params = {}) => request({
    url: '/ai/business/flow/task-form-context',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  getBusinessTaskReadonlyContext: (params = {}) => request({
    url: '/ai/business/flow/task-form-context/readonly',
    method: 'get',
    params,
    encrypt: true,
    needTip: false,
  }),
  saveBusinessTaskFormContext: data => request({
    url: '/ai/business/flow/task-form-context',
    method: 'put',
    data,
    encrypt: true,
  }),
  completeBusinessTaskAction: data => request({
    url: '/ai/business/flow/task-action',
    method: 'post',
    data,
    encrypt: true,
  }),
  getMessagePage: (params = {}) => {
    const {
      pageNum = 1,
      pageSize = 10,
      ...query
    } = params || {}
    return request({
      url: '/api/message/page',
      method: 'post',
      params: { pageNum, pageSize },
      data: query,
      encrypt: true,
      needTip: false,
    })
  },
  getMessageDetail: id => request({
    url: `/api/message/${id}`,
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  getUnreadMessageCount: () => request({
    url: '/api/message/unread/count',
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  markMessageRead: id => request({
    url: `/api/message/${id}/read`,
    method: 'post',
    data: {},
    encrypt: true,
    needTip: false,
  }),
  markMessagesReadBatch: ids => request({
    url: '/api/message/read/batch',
    method: 'post',
    data: Array.isArray(ids) ? ids : [],
    encrypt: true,
    needTip: false,
  }),
  markAllMessagesRead: () => request({
    url: '/api/message/read/all',
    method: 'post',
    data: {},
    encrypt: true,
    needTip: false,
  }),
  getEnabledMessageBizTypes: () => request({
    url: '/api/message/bizType/list/enabled',
    method: 'get',
    encrypt: true,
    needTip: false,
  }),
  getNoticePage: (params = {}) => request({
    url: '/system/notice/user/page',
    method: 'get',
    params,
    needTip: false,
  }),
  getNoticeUnreadCount: () => request({
    url: '/system/notice/user/unread-count',
    method: 'get',
    needTip: false,
  }),
  getNoticeDetail: noticeId => request({
    url: `/system/notice/user/${encodeURIComponent(String(noticeId || ''))}`,
    method: 'get',
    needTip: false,
  }),
  markNoticeRead: noticeId => request({
    url: '/system/notice/markAsRead',
    method: 'post',
    params: { noticeId },
    data: {},
    encrypt: true,
    needTip: false,
  }),
  getStartableObjects: () => request({
    url: '/ai/business/flow/startable-objects',
    method: 'get',
    needTip: false,
  }),
  getBusinessDocumentRuntime: (objectCode, recordId) => request({
    url: `/ai/business/document/${encodeURIComponent(String(objectCode || ''))}/${encodeURIComponent(String(recordId || ''))}/runtime`,
    method: 'get',
    needTip: false,
  }),
  getBusinessFlowStartConfig: objectCode => request({
    url: `/ai/business/flow/start-config/${encodeURIComponent(String(objectCode || ''))}`,
    method: 'get',
    needTip: false,
  }),
  startBusinessDocumentFlow: data => request({
    url: '/ai/business/flow/start',
    method: 'post',
    data,
    encrypt: true,
    needTip: false,
  }),
  resubmitBusinessDocumentFlow: data => request({
    url: '/ai/business/flow/resubmit',
    method: 'post',
    data,
    encrypt: true,
    needTip: false,
  }),
  withdrawBusinessDocumentFlow: data => request({
    url: '/ai/business/flow/withdraw',
    method: 'post',
    data,
    encrypt: true,
    needTip: false,
  }),
  getTenantConfig: tenantId => request({
    url: '/system/tenant/userTenantConfig',
    method: 'post',
    data: { id: tenantId },
  }),
  getCurrentTenantOptions: () => request({
    url: '/system/tenant/current/options',
    method: 'get',
  }),
  switchTenant: tenantId => request({
    url: '/system/tenant/switch',
    method: 'post',
    params: { tenantId },
  }),

  // 通用低代码运行时。H5 与管理端共用发布态协议和动态 CRUD，后端由 app-server 暴露同一套运行接口。
  getLowcodeRenderConfig: (configKey, params = {}) => request({
    url: `/ai/crud-config/render/${encodeURIComponent(configKey)}`,
    method: 'get',
    params,
    needTip: false,
  }),
  getLowcodePage: (configKey, params = {}) => request({
    url: `/ai/crud/${encodeURIComponent(configKey)}/page`,
    method: 'get',
    params,
    needTip: false,
  }),
  getLowcodeDetail: (configKey, id) => request({
    url: `/ai/crud/${encodeURIComponent(configKey)}/${encodeURIComponent(id)}`,
    method: 'get',
    needTip: false,
  }),
  createLowcodeRecord: (configKey, data) => request({
    url: `/ai/crud/${encodeURIComponent(configKey)}`,
    method: 'post',
    data,
    encrypt: true,
  }),
  updateLowcodeRecord: (configKey, data) => request({
    url: `/ai/crud/${encodeURIComponent(configKey)}`,
    method: 'put',
    data,
    encrypt: true,
  }),
  deleteLowcodeRecord: (configKey, id) => request({
    url: `/ai/crud/${encodeURIComponent(configKey)}/${encodeURIComponent(id)}`,
    method: 'delete',
    needTip: false,
  }),
  getDictOptions: dictType => request({
    url: `/system/dict/data/type/${encodeURIComponent(dictType)}`,
    method: 'get',
    needTip: false,
  }),
  executeLowcodeQuerySource: (data, options = {}) => request({
    ...options,
    url: '/ai/lowcode/query-source/execute',
    method: 'post',
    data,
    encrypt: true,
    needTip: false,
  }),
  queryBusinessRecordSelector: (data, params = {}) => request({
    url: '/ai/business/selector/query',
    method: 'post',
    params,
    data,
    encrypt: true,
    needTip: false,
  }),
  executeLowcodeOptionRequest: ({ method = 'get', url, params = {} }) => request({
    url,
    method,
    params: method === 'get' ? params : undefined,
    data: method === 'post' ? params : undefined,
    needTip: false,
  }),
  executeBusinessAction: data => request({
    url: '/ai/business/action/execute',
    method: 'post',
    data,
    encrypt: true,
  }),
}
