package com.mdframe.forge.plugin.generator.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.mdframe.forge.plugin.generator.domain.entity.AiCrudConfig;
import com.mdframe.forge.plugin.generator.service.businessapp.CodeRuleService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@DisplayName("DynamicCrudService auto generation")
class DynamicCrudServiceAutoGenerationTest {

    private final FakeDynamicCrudRepository repository = new FakeDynamicCrudRepository();
    private final FakeCodeRuleService codeRuleService = new FakeCodeRuleService();
    private final DynamicCrudService service = new DynamicCrudService(
            repository,
            null,
            new ObjectMapper(),
            null,
            null,
            null,
            null,
            null,
            codeRuleService,
            null,
            null,
            null,
            null);

    @Test
    @DisplayName("generates conventional code field when explicit generation config is absent")
    void generatesConventionalCodeFieldWhenGenerationConfigAbsent() throws Exception {
        AiCrudConfig config = materialConfig();
        repository.setColumnMapping(Map.of(
                "materialCode", "material_code",
                "material_code", "material_code",
                "materialName", "material_name",
                "material_name", "material_name"
        ));
        codeRuleService.setGeneratedCode("material_code", "WL00001");
        Map<String, Object> data = new LinkedHashMap<>();
        data.put("materialCode", null);
        data.put("materialName", "水泥");
        Set<String> allowedFields = new LinkedHashSet<>(Set.of("materialCode", "materialName"));

        applyAutoGeneratedFields(config, data, allowedFields);

        assertEquals("WL00001", data.get("materialCode"));
        assertEquals("WL00001", data.get("material_code"));
        assertTrue(allowedFields.contains("materialCode"));
        assertTrue(allowedFields.contains("material_code"));
        assertEquals("material_code", codeRuleService.getLastRuleCode());
        assertEquals("水泥", ((Map<?, ?>) codeRuleService.getLastContext().get("fields")).get("materialName"));
        assertEquals("PW_MATERIAL", ((Map<?, ?>) codeRuleService.getLastContext().get("fields")).get("objectCode"));
        assertNull(codeRuleService.getLastContext().get("tenantId"));
    }

    @Test
    @DisplayName("keeps user entered code for empty-only conventional field")
    void keepsUserEnteredCodeForEmptyOnlyConventionalField() throws Exception {
        AiCrudConfig config = materialConfig();
        repository.setColumnMapping(Map.of(
                "materialCode", "material_code",
                "material_code", "material_code"
        ));
        Map<String, Object> data = new LinkedHashMap<>();
        data.put("materialCode", "CUSTOM-001");

        applyAutoGeneratedFields(config, data, new LinkedHashSet<>());

        assertEquals("CUSTOM-001", data.get("materialCode"));
        assertEquals(0, codeRuleService.getGenerateCalls());
    }

    @Test
    @DisplayName("does not apply conventional fallback when generation is explicitly configured")
    void doesNotApplyFallbackWhenGenerationExplicitlyConfigured() throws Exception {
        AiCrudConfig config = materialConfigWithDisabledGeneration();
        repository.setColumnMapping(Map.of(
                "materialCode", "material_code",
                "material_code", "material_code"
        ));
        codeRuleService.setGeneratedCode("material_code", "WL00001");
        Map<String, Object> data = new LinkedHashMap<>();
        data.put("materialCode", null);

        applyAutoGeneratedFields(config, data, new LinkedHashSet<>());

        assertNull(data.get("materialCode"));
        assertEquals(0, codeRuleService.getGenerateCalls());
    }

    @SuppressWarnings("unchecked")
    private void applyAutoGeneratedFields(AiCrudConfig config,
                                          Map<String, Object> data,
                                          Set<String> allowedFields) throws Exception {
        Method method = DynamicCrudService.class.getDeclaredMethod(
                "applyAutoGeneratedFields", AiCrudConfig.class, Map.class, Set.class);
        method.setAccessible(true);
        method.invoke(service, config, data, allowedFields);
    }

    private AiCrudConfig materialConfig() {
        AiCrudConfig config = new AiCrudConfig();
        config.setTenantId(1L);
        config.setConfigKey("pw_material");
        config.setObjectCode("PW_MATERIAL");
        config.setTableName("pw_material");
        config.setModelSchema("""
                {
                  "tableName": "pw_material",
                  "fields": [
                    {
                      "field": "materialCode",
                      "columnName": "material_code",
                      "label": "物料编号",
                      "dataType": "varchar",
                      "length": 64,
                      "required": true
                    },
                    {
                      "field": "materialName",
                      "columnName": "material_name",
                      "label": "物料名称",
                      "dataType": "varchar",
                      "length": 128,
                      "required": true
                    }
                  ]
                }
                """);
        config.setEditSchema("""
                [
                  {"field": "materialCode", "label": "物料编号", "type": "input"},
                  {"field": "materialName", "label": "物料名称", "type": "input"}
                ]
                """);
        return config;
    }

    private AiCrudConfig materialConfigWithDisabledGeneration() {
        AiCrudConfig config = materialConfig();
        config.setModelSchema("""
                {
                  "tableName": "pw_material",
                  "fields": [
                    {
                      "field": "materialCode",
                      "columnName": "material_code",
                      "label": "物料编号",
                      "dataType": "varchar",
                      "length": 64,
                      "required": true,
                      "basicProps": {
                        "generation": {
                          "enabled": false,
                          "ruleCode": "material_code"
                        }
                      }
                    }
                  ]
                }
                """);
        return config;
    }

    private static class FakeDynamicCrudRepository extends DynamicCrudRepository {

        private Map<String, String> columnMapping = Map.of();

        FakeDynamicCrudRepository() {
            super(null, null, null);
        }

        void setColumnMapping(Map<String, String> columnMapping) {
            this.columnMapping = columnMapping;
        }

        @Override
        public Map<String, String> getColumnMapping(String tableName) {
            return columnMapping;
        }
    }

    private static class FakeCodeRuleService extends CodeRuleService {

        private final Map<String, String> generatedCodes = new LinkedHashMap<>();
        private int generateCalls;
        private String lastRuleCode;
        private Map<String, Object> lastContext;

        FakeCodeRuleService() {
            super(null, null, null);
        }

        void setGeneratedCode(String ruleCode, String generatedCode) {
            generatedCodes.put(ruleCode, generatedCode);
        }

        int getGenerateCalls() {
            return generateCalls;
        }

        String getLastRuleCode() {
            return lastRuleCode;
        }

        Map<String, Object> getLastContext() {
            return lastContext;
        }

        @Override
        public String generate(String ruleCode, Map<String, Object> context) {
            generateCalls++;
            lastRuleCode = ruleCode;
            lastContext = context;
            return generatedCodes.get(ruleCode);
        }
    }
}
