# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8580
  servlet:
    # 应用的访问路径
    context-path: /
  # undertow 配置
  undertow:
    # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
    max-http-post-size: -1
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 8
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 256

# 日志配置
logging:
  level:
    com.forge: @logging.level@
    org.springframework: error
    org.mybatis.spring.mapper: error
  config: classpath:logback.xml

# Spring配置
spring:
  application:
    name: ${project.name}
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: @profiles.active@
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  mvc:
    # 设置静态资源路径 防止所有请求都去查静态资源
    static-path-pattern: /static/**
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent_output: false
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false

# MyBatisPlus配置
# https://baomidou.com/config/
mybatis-plus:
  # 多包名使用
  mapperPackage: com.mdframe.forge.**.mapper
  # 对应的 XML 文件位置
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mdframe.forge.**.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    useGeneratedKeys: true
    defaultExecutorType: SIMPLE
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    dbConfig:
      # 主键类型
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      # 如需改为自增 需要将数据库表全部设置为自增
      idType: ASSIGN_ID
# Sa-Token 配置
sa-token:
  # 使用Redis存储Session
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: ${spring.data.redis.host}
    # Redis服务器连接端口
    port: ${spring.data.redis.port}
    # Redis服务器连接密码（默认为空）
    password: ${spring.data.redis.password}
    # 连接超时时间（毫秒）
    timeout: 10000
sms:
  config-type: interface
